dist: trusty
sudo: false

language: scala

scala:
  - 2.12.6
  - 2.11.12

jdk: oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "lzVkSSCfW/ktaoIEe+XQstIbz0hrShnHejHnDq/Lptyt2TtTaGSkkXY3ZP3w1c4z7JZzIQlcGl/Zqb0COfBkcXid4PidrmmaQPiwWLxkzibMY6AVo/HX5codVuxxizlEfw1UpAwNnTUdKmJ88DG1lgSj70Cxsf6eLdKpmkxL/NsTKI2xKrki3/vyQwn5CAaLRxwHMWwjWh/zP/p0HBURmMBgzsPqZ0y59Y60T+aCD020UBa3L+JvKvwmVURsb0h98A86ahUUCIf5cOXS9WyEt+dpaT38mIPZNDpLJeQ5a1JeJ/RpnHauI5xwYnYzu/Ls6ZgEcvxxIHpdNX0qvg27oXSa9xkVebKqBPCzzWzvpRQpuLJc8XwWZPVW7ZwcAAjm8L8w16qs9226jy64FXDlyk3bPUpGjYSJs8CmxhgouriOpqtaukCJdvjBjSeCwCMf7d4b+6N2RXBwPTaRgrHkOSuCzJtc1n5ui2bu1eEHPy9RCD0m4iusN/K9gdRS7rPz1Dg7X0Lu9INHCoUDiove3dluPjZYpJAx7kU+fs6Kyh7Jmgq8PQsCJJPuGoy0dMduullskA33O+1QCSc5Vch6gTnwkBUpnXwXW2oFe5Y2RO9RfgEHMi3PRCJp5JudZYyrnUI1VkhdmQROIdCJYV0OhD4hGwj3hLiXD/Mk2KycBxE="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete